# Generated by Django 2.1.5 on 2019-03-02 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=8)),
                ('user_name', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=2)),
                ('gender', models.BooleanField(default=True)),
                ('creation_date', models.DateField(default=datetime.datetime(2019, 3, 2, 4, 27, 2, 908412))),
            ],
        ),
    ]
