# Generated by Django 2.1.5 on 2019-03-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190302_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField()),
                ('role', models.CharField(max_length=5)),
                ('user_id', models.ForeignKey(on_delete=True, to='app1.UserInfo')),
            ],
        ),
    ]
